### ISSUE TITLE
Simple example breaks at pip install

### ISSUE THREAD

**Issue by balopat** [treebeardtech/treebeard#62]
**Describe the bug**
```
  /usr/bin/pip install nbmake==0.1
  Collecting nbmake==0.1
    Downloading https://files.pythonhosted.org/packages/80/d9/21b4c9ecf94ec23593590d518c338a3d55c10c2fbc1a1bd0187677fd010e/nbmake-0.1.tar.gz
  Collecting PyYAML<6.0.0,>=5.3.1 (from nbmake==0.1)
    Downloading https://files.pythonhosted.org/packages/ba/d4/3cf562876e0cda0405e65d351b835077ab13990e5b92912ef2bf1a2280e0/PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574kB)
  Collecting Pygments<3.0.0,>=2.7.3 (from nbmake==0.1)
    Downloading https://files.pythonhosted.org/packages/e1/86/8059180e8217299079d8719c6e23d674aadaba0b1939e25e0cc15dcf075b/Pygments-2.7.4.tar.gz (2.3MB)
  Collecting ipykernel<6.0.0,>=5.4.0 (from nbmake==0.1)
    Downloading https://files.pythonhosted.org/packages/5e/bf/a7184ba49ff503ca6328e5331d71e08ee446255009ef7b4bfd7e3adf60a5/ipykernel-5.4.3.tar.gz (111kB)
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-XduGRn/ipykernel/setup.py", line 19
          print(error, file=sys.stderr)
                           ^
      SyntaxError: invalid syntax
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XduGRn/ipykernel/
  You are using pip version 8.1.1, however version 21.0.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  Error: The process '/usr/bin/pip' failed with exit code 1
```

**To Reproduce**
simple workflows/ci.yaml

```
name: Continuous Integration

on: [pull_request]

jobs:

  notebooks-branch:
    name: Notebook Tests (branch)
    runs-on: ubuntu-16.04
    steps:
      - name: nbmake
        uses: treebeardtech/nbmake-action@v0.2.1

```

**Expected behavior**
The action to run. 

**Screenshots**
https://github.com/balopat/Cirq/pull/9/checks?check_run_id=1827319748
